# TFL Project

## Step 1: Data Preparation
- Import data.
- Merge datasets into one dataframe.
- Format data correctly as we want it.
- Create the necessary variables.
- Check the data

In [2]:
# Imports for Step 1
import pandas as pd

### Step 1A: Import Data

In [3]:
# Import the datasets
df2019 = pd.read_csv("StationFootfall_2019.csv")
df2020 = pd.read_csv("StationFootfall_2020.csv")
df2021 = pd.read_csv("StationFootfall_2021.csv")
df2022 = pd.read_csv("StationFootfall_2022.csv")
df2023 = pd.read_csv("StationFootfall_2023.csv")
df2024 = pd.read_csv("StationFootfall_2024.csv")
df2025 = pd.read_csv("stationfootfall-2025.csv")

### Step 1B: Merge Datasets

In [4]:
# Ready the data to be merged
df2019 = df2019.rename(columns={"DayOFWeek": "DayOfWeek"})
df2020 = df2020.rename(columns={"DayOFWeek": "DayOfWeek"})
df2021 = df2021.rename(columns={"DayOFWeek": "DayOfWeek"})
df2022 = df2022.rename(columns={"DayOFWeek": "DayOfWeek"})

In [5]:
# Merge the dataset
df = pd.concat([
    df2019,
    df2020,
    df2021,
    df2022,
    df2023,
    df2024,
    df2025
], ignore_index=True)

### Step 1C: Format Data

In [6]:
# Format variable names
df = df.rename(columns = {'TravelDate': 'date'})
df = df.rename(columns = {'DayOfWeek': 'day'})
df = df.rename(columns = {'Station': 'station'})
df = df.rename(columns = {'EntryTapCount': 'enter_count'})
df = df.rename(columns = {'ExitTapCount': 'exit_count'})

In [7]:
# Format the time variable
df["date"] = pd.to_datetime(df["date"], format="%Y%m%d")

### Step 1D: Create necessary variables

In [8]:
# Create total variable
df["total_count"] = df["enter_count"] + df["exit_count"]

In [9]:
# Create year and month variables
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month

In [10]:
# Create weekend variable
df["is_weekend"] = df["day"].isin(
    ["Saturday", "Sunday"]
)

In [11]:
# Create the month name variable
df["month_name"] = pd.to_datetime(
    df["month"], format="%m"
).dt.month_name()

In [12]:
# Create a COVID variable
df["covid_period"] = df["year"].apply(
    lambda x: "Pre-COVID" if x == 2019
    else "COVID" if x in [2020, 2021]
    else "Post-COVID"
)

### Step 1D: Check the data

In [13]:
# Check for duplicates
df.duplicated(
    subset=["date", "station"]
).sum()

np.int64(0)

In [14]:
# Check extreme values
(df[["enter_count", "exit_count", "total_count"]] < 0).sum()

enter_count    0
exit_count     0
total_count    0
dtype: int64

In [15]:
# Check years
df["year"].unique()

array([2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026], dtype=int32)

## Step 2: Exploratory Statistics
- Generate Descriptive statistics
- Generate key facts about the datasets
- Visualise these facts

### Step 2A: Generate Descriptive Statistics

In [16]:
df[[ # descrptive statistics
    "enter_count",
    "exit_count",
    "total_count"
]].describe()

        enter_count    exit_count   total_count
count  1.160147e+06  1.160147e+06  1.160147e+06
mean   7.696729e+03  7.720585e+03  1.541731e+04
std    1.287758e+04  1.320902e+04  2.605442e+04
min    0.000000e+00  0.000000e+00  0.000000e+00
25%    1.682000e+03  1.621000e+03  3.309000e+03
50%    3.718000e+03  3.620000e+03  7.346000e+03
75%    7.877000e+03  7.783000e+03  1.566500e+04
max    1.614980e+05  1.805380e+05  3.299810e+05

### Step 2B: Generate Key facts

In [ ]:
# Top 10 most popular station across our whole dataset
df.groupby('station')['total_count'].sum().sort_values(ascending=False).head(10)

station
Kings Cross St Pancras    481508056
Victoria                  417222116
Waterloo                  380627273
London Bridge             380583303
Stratford                 373111069
Oxford Circus             366423120
Liverpool Street          366029199
Tottenham Court Road      317876745
Bond Street               234688786
Paddington                219757274
Name: total_count, dtype: int64

In [25]:
# Bottom 10 most popular station across our whole dataset
df.groupby('station')['total_count'].sum().sort_values(ascending=True).head(10)

station
Unknown             824606
Taplow              865383
Iver                891035
Roding Valley      1169651
Twyford            1227787
Emerson Park       1289291
Beckton Park       1971455
Chigwell           2214338
Langley Berks      2248241
South Hampstead    2685946
Name: total_count, dtype: int64

In [ ]:
# Top 10 daily average station across our whole dataset
df.groupby("station")["total_count"].mean().sort_values(ascending=False).head(10)

station
Kings Cross St Pancras    175861.233017
Victoria                  152437.747899
London Bridge             139102.084430
Waterloo                  138965.780577
Stratford                 136371.004751
Oxford Circus             133779.890471
Liverpool Street          133587.298905
Tottenham Court Road      116055.766703
Bond Street                85746.724881
Paddington                 80232.666667
Name: total_count, dtype: float64

In [28]:
# Bottom 10 daily average station across our whole dataset
df.groupby("station")["total_count"].mean().sort_values(ascending=True).head(10)

station
Taplow              418.666183
Iver                431.076439
Roding Valley       431.605535
Emerson Park        492.659916
Twyford             596.592323
Beckton Park        729.628053
Unknown             793.653513
Chigwell            813.197943
Grange Hill        1003.575735
South Hampstead    1019.334345
Name: total_count, dtype: float64

In [32]:
# Most taps per month
df.groupby("month_name")["total_count"].mean().sort_values(ascending=False).head(3)

month_name
October     16917.104841
November    16809.058730
February    16477.355371
Name: total_count, dtype: float64

In [37]:
# Least taps per month
df.groupby("month_name")["total_count"].mean().sort_values(ascending=True).head(3)

month_name
April     14159.917764
August    14394.981381
May       14788.062785
Name: total_count, dtype: float64

In [ ]:
# Most taps per day
df.groupby("day")["total_count"].mean().sort_values(ascending=False).head(3)

day
Thursday     17638.488870
Wednesday    17251.763767
Tuesday      16909.124404
Name: total_count, dtype: float64

In [35]:
# Least taps per day
df.groupby("day")["total_count"].mean().sort_values(ascending=True).head(3)

day
Sunday       9998.440027
Saturday    14288.744912
Monday      14996.602167
Name: total_count, dtype: float64

### Step 3: Analysis

In [ ]:
# Total taps per year by station
annual_df = (df.groupby(["station", "year"])["total_count"].sum().unstack())

In [ ]:
# Growth variable
annual_df["growth_pct"] = ((yearly[2025] - yearly[2019]) / yearly[2019]) * 100

In [ ]:
# Higehst growth in demand for station usage from 2019 to 2025 (All Lizzy line stations)
annual_df.sort_values("growth_pct", ascending=False).head(10)

year,2019,2020,2021,2022,2023,2024,2025,2026,growth_pct
station,,,,,,,,,
Slough,93.0,122900.0,387768.0,767789.0,1514094.0,1855484.0,2037575.0,1058089.0,2.190841e+06
Reading,126.0,68208.0,202767.0,419811.0,772969.0,953081.0,1065972.0,571383.0,8.459095e+05
Acton Main Line,303004.0,162829.0,274219.0,877171.0,2034988.0,2533196.0,2809853.0,1523514.0,8.273320e+02
Heathrow T2&3 TfL Rail/HEx,828561.0,239270.0,274775.0,2089628.0,4948106.0,5896284.0,6587186.0,3665794.0,6.950152e+02
Heathrow T5 TfL Rail/HEx,491840.0,201329.0,231236.0,1220010.0,2748389.0,3434918.0,3837321.0,2062946.0,6.801970e+02
Heathrow T4 TfL Rail/HEx,381401.0,78435.0,315.0,321925.0,1206686.0,1665358.0,1878535.0,1054908.0,3.925354e+02
Hanwell,398291.0,220430.0,411862.0,807685.0,1346081.0,1548931.0,1687025.0,932236.0,3.235659e+02
Abbey Wood,3274465.0,1687009.0,1959639.0,4613529.0,8610234.0,10439767.0,11667552.0,6141261.0,2.563193e+02
Maryland,1276017.0,759733.0,1198636.0,1880992.0,3107610.0,3758137.0,4011495.0,2078686.0,2.143763e+02
Southall,2769700.0,1445936.0,2114143.0,3628793.0,5837635.0,6812679.0,7324050.0,3696569.0,1.644348e+02